<!-- <div class="welcome-footer">
	<?php 
		$copy = str_replace('{site_name}', $wo['config']['siteName'], $wo['lang']['copyrights']);
		echo $copy = str_replace('{date}', date('Y'), $copy);
	?> &nbsp;•&nbsp;
	<a data-ajax="?link1=terms&type=terms" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=terms');?>"><?php echo $wo['lang']['terms_of_use'];?></a> &nbsp;•&nbsp;
	<a data-ajax="?link1=terms&type=privacy-policy" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=privacy-policy');?>"><?php echo $wo['lang']['privacy_policy'];?></a> &nbsp;•&nbsp;
	<a data-ajax="?link1=contact-us" href="<?php echo Wo_SeoLink('index.php?link1=contact-us');?>"><?php echo $wo['lang']['contact_us'];?></a> &nbsp;•&nbsp;
	<a data-ajax="?link1=terms&type=about-us" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=about-us');?>"><?php echo $wo['lang']['about'];?></a> &nbsp;•&nbsp;
	
	<?php  if ($wo['config']['forum'] == 1 && $wo['config']['forum_visibility'] == 0) { ?>
		<a href="<?php echo Wo_SeoLink('index.php?link1=forum');?>" data-ajax="?link1=forum"><?php echo $wo['lang']['forum'];?></a> &nbsp;•&nbsp;
	<?php } ?>
	<?php  if ($wo['config']['events'] == 1 && $wo['config']['events_visibility'] == 0) { ?>
		<a href="<?php echo Wo_SeoLink('index.php?link1=events');?>" data-ajax="?link1=events"><?php echo $wo['lang']['events'];?></a> &nbsp;•&nbsp;
	<?php } ?>
	<?php  if ($wo['config']['classified'] == 1 && $wo['config']['product_visibility'] == 0) { ?>
		<a href="<?php echo Wo_SeoLink('index.php?link1=products');?>" data-ajax="?link1=products"><?php echo $wo['lang']['market'];?></a> &nbsp;•&nbsp;
	<?php } ?>
	<?php
		$pages = Wo_GetCustomPages();
		if (count($pages) > 0) {
		foreach ($pages as $key => $page) {
	?>
		<a href="<?php echo Wo_SeoLink('index.php?link1=site-pages&page_name=' . $page['page_name']);?>"><?php echo $page['page_title'];?></a> &nbsp;•&nbsp;
	<?php } } ?>
	
</div> -->