<div id="ProfileImageModal-<?php echo $wo['user_profile']['user_id'];?>" class="modal fade image-modal" tabindex="-1" role="dialog" aria-hidden="true">
   <div class="modal-dialog profile-picture">
      <div class="modal-content">
         <div class="modal-body">
            <img src="<?php echo $wo['user_profile']['avatar'];?>" id="updateImage-<?php echo $wo['user_profile']['user_id']?>"  class="img-responsive" onerror="this.src='/themes/wowonder/img/profile_image_not_found.png';"/>
         </div>
      </div>
   </div>
</div>