<div class="sidebar-user-data">
   <a href="<?php echo $wo['GroupList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['GroupList']['username']?>">
      <div class="sidebar-listed-user-avatar">
         <img src="<?php echo $wo['GroupList']['avatar']?>" onerror="this.src='/themes/wowonder/img/profile_image_not_found.png';">
      </div>
      <div class="sidebar-listed-user-name"><?php echo $wo['GroupList']['name'];?></div>
   </a>
</div>