<div class="sidebar-user-data">
   <a href="<?php echo $wo['album']['url'];?>" data-ajax="?link1=post&id=<?php echo $wo['album']['id']?>" data-toggle="tooltip" title = "<?php echo $wo['album']['album_name']; ?>">
      <div class="sidebar-listed-user-avatar">
      	<?php if ($wo['album']['blur'] == 1) { ?>
      		<img src="<?php echo $wo['album']['first_image']?>" class="image_blur" onerror="this.src='/themes/wowonder/img/profile_image_not_found.png';">
      	<?php }else{ ?>
      		<img src="<?php echo $wo['album']['first_image']?>" onerror="this.src='/themes/wowonder/img/profile_image_not_found.png';">
      	<?php } ?>
      </div>
      <div class="sidebar-listed-user-name"><?php echo $wo['album']['album_name'];?></div>
   </a>
</div>