<div class="container-fluid">
    <div>
        <h3>Manage Website Features</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Settings</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Manage Website Features</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-7 col-md-7">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Manage Website Features</h6>
                    <div class="site-settings-alert"></div>
                    <form class="site-settings" method="POST">
                        
                        <div class="clearfix"></div>
                        

                        
                        <div class="clearfix"></div>
                        
                        
                        
                        <div class="clearfix"></div>
                        
                        
                        
                        <div class="clearfix"></div>
                        

                        
                        <div class="clearfix"></div>
                        

                      
                        <div class="clearfix"></div>

                       
                        <div class="clearfix"></div>

                        

                        
                        <div class="clearfix"></div>

                        
                        <div class="clearfix"></div>

                        

                        

                        

                        

                        
                        

                        

                        

                        <div class="float-left">
                            <label for="job_system" class="main-label">Jobs System</label>
                            <br><small class="admin-info">Allow pages to create jobs, users can apply and get hired.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="job_system" value="0" />
                            <input type="checkbox" name="job_system" id="chck-job_system" value="1" <?php echo ($wo['config']['job_system'] == 1) ? 'checked': '';?> <?php echo(EnableForMode('job_system')) ?>>
                            <label for="chck-job_system" class="check-trail <?php echo(EnableForMode('job_system',true)) ?>" <?php echo(EnableForMode('job_system',false,true)) ?>><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>

                       
                        
                        <div class="clearfix"></div>

                        <!-- <label for="weather_widget">Weather Widget</label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="weather_widget" id="weather_widget-enabled" value="1" <?php echo ($wo['config']['weather_widget'] == 1) ? 'checked': '';?> <?php echo(EnableForMode('poke_system')) ?>>
                                <label  class="form-check-label" for="weather_widget-enabled">Enabled</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="weather_widget" id="weather_widget-disabled" value="0" <?php echo ($wo['config']['weather_widget'] == 0) ? 'checked': '';?> <?php echo(EnableForMode('poke_system')) ?>>
                                <label  class="form-check-label" for="weather_widget-disabled" class="m-l-20">Disabled</label>
                            </div>
                        </div> -->
                        <!-- <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Openweathermap Weather App Id</label>
                                <input type="text" id="weather_key" name="weather_key" class="form-control" value="<?php echo $wo['config']['weather_key']?>">
                            </div>
                        </div> -->
                        <!-- 
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Yahoo Weather Consumer Key</label>
                                <input type="text" id="yahoo_consumer_key" name="yahoo_consumer_key" class="form-control" value="<?php echo $wo['config']['yahoo_consumer_key']?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Yahoo Weather Consumer Secret</label>
                                <input type="text" id="yahoo_consumer_secret" name="yahoo_consumer_secret" class="form-control" value="<?php echo $wo['config']['yahoo_consumer_secret']?>">
                            </div>
                        </div> -->
                        
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
        </div>
        
        <div class="col-lg-5 col-md-5">
            <div class="card">
                
            </div>
        </div>
        
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>
$(function() {
    $('.switcher input[type=checkbox]').click(function () {
        setToTrue = 0;
        if ($(this).is(":checked") === true) {
            setToTrue = 1;
        }
        var configName = $(this).attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        objData[configName] = setToTrue;
        objData['hash_id'] = hash_id;
        $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData);
    });

    var setTimeOutColor = setTimeout(function (){});
    $('select').on('change', function() {
         clearTimeout(setTimeOutColor);
        var thisElement = $(this);
        var configName = thisElement.attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        objData[configName] = this.value;
        objData['hash_id'] = hash_id;
        thisElement.addClass('warning');
        $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function (data) {
            if (data.status == 200) {
                thisElement.removeClass('warning');
                thisElement.addClass('success');
            } else {
                thisElement.addClass('error');
            }
            var setTimeOutColor = setTimeout(function () {
                thisElement.removeClass('success');
                thisElement.removeClass('warning');
                thisElement.removeClass('error');
            }, 2000);
        });
    });
    $('input[type=text], input[type=number], textarea').on('keyup', delay(function() {
            clearTimeout(setTimeOutColor);
            var thisElement = $(this);
            var configName = thisElement.attr('name');
            var hash_id = $('input[name=hash_id]').val();
            var objData = {};
            objData[configName] = this.value;
            objData['hash_id'] = hash_id;
            thisElement.addClass('warning');
            $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function (data) {
                if (data.status == 200) {
                    thisElement.removeClass('warning');
                    thisElement.addClass('success');
                } else {
                    thisElement.addClass('error');
                }
                var setTimeOutColor = setTimeout(function () {
                    thisElement.removeClass('success');
                    thisElement.removeClass('warning');
                    thisElement.removeClass('error');
                }, 2000);
                //thisElement.focus();
            });
    }, 500));
});

</script>